namespace CouponCalculator.Models;

public class CalculationTemplate
{
    public string TemplateId { get; set; } = Guid.NewGuid().ToString();
    public string TemplateName { get; set; } = string.Empty;
    public string TemplateDescription { get; set; } = string.Empty;
    public string Category { get; set; } = string.Empty;
    
    public TemplateType Type { get; set; }
    public TemplateSource Source { get; set; }
    
    public DateTime CreatedAt { get; set; }
    public DateTime? LastUsedAt { get; set; }
    public int UsageCount { get; set; }
    
    public string CreatedBy { get; set; } = string.Empty;
    public List<string> Tags { get; set; } = new();
    
    public TemplateSnapshot Snapshot { get; set; } = new();
    
    public List<TemplateVersion> Versions { get; set; } = new();
    
    public bool IsActive { get; set; } = true;
    public DateTime? ExpiresAt { get; set; }
    
    public Dictionary<string, string> Metadata { get; set; } = new();
}

public enum TemplateType
{
    Trial,
    Order,
    Refund,
    Custom
}

public enum TemplateSource
{
    Manual,
    AutoGenerated,
    Imported,
    System
}

public class TemplateSnapshot
{
    public string OrderId { get; set; } = string.Empty;
    public DateTime SnapshotTime { get; set; }
    
    public OrderContextSnapshot OrderSnapshot { get; set; } = new();
    public List<CouponSnapshot> CouponsSnapshot { get; set; } = new();
    
    public CalculationResult Result { get; set; } = new();
    public EnhancedCalculationResult EnhancedResult { get; set; } = new();
    public ItemLevelDiscountBreakdown Breakdown { get; set; } = new();
    
    public List<string> AppliedRuleIds { get; set; } = new();
    public List<string> AppliedCouponIds { get; set; } = new();
    
    public Explanation Explanation { get; set; } = new();
    public string UserExplanation { get; set; } = string.Empty;
    
    public Dictionary<string, string> ContextMetadata { get; set; } = new();
}

public class TemplateVersion
{
    public int VersionNumber { get; set; }
    public DateTime CreatedAt { get; set; }
    public string CreatedBy { get; set; } = string.Empty;
    public string ChangeNote { get; set; } = string.Empty;
    public TemplateSnapshot Snapshot { get; set; } = new();
}

public class TemplatePlaybackRequest
{
    public string TemplateId { get; set; } = string.Empty;
    public string? TargetOrderId { get; set; }
    public Dictionary<string, object> ParameterOverrides { get; set; } = new();
    public bool ValidateOnly { get; set; } = false;
    public bool GenerateExplanation { get; set; } = true;
}

public class TemplatePlaybackResult
{
    public string PlaybackId { get; set; } = Guid.NewGuid().ToString();
    public string TemplateId { get; set; } = string.Empty;
    public string TemplateName { get; set; } = string.Empty;
    
    public bool IsMatch { get; set; }
    public decimal MatchScore { get; set; }
    
    public TemplateSnapshot? OriginalSnapshot { get; set; }
    public CalculationResult? CurrentResult { get; set; }
    public EnhancedCalculationResult? CurrentEnhancedResult { get; set; }
    
    public List<TemplateDifference> Differences { get; set; } = new();
    
    public string Explanation { get; set; } = string.Empty;
    public List<string> Warnings { get; set; } = new();
    
    public DateTime PlayedAt { get; set; }
}

public class TemplateDifference
{
    public string Field { get; set; } = string.Empty;
    public string Category { get; set; } = string.Empty;
    public string OldValue { get; set; } = string.Empty;
    public string NewValue { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    public bool IsSignificant { get; set; }
}

public class TemplateComparison
{
    public string ComparisonId { get; set; } = Guid.NewGuid().ToString();
    public string TemplateId1 { get; set; } = string.Empty;
    public string TemplateId2 { get; set; } = string.Empty;
    
    public DateTime ComparedAt { get; set; }
    
    public List<TemplateDifference> Differences { get; set; } = new();
    public List<TemplateDifference> SignificantDifferences { get; set; } = new();
    
    public decimal TotalDifference { get; set; }
    public decimal PercentageDifference { get; set; }
    
    public string GenerateComparisonReport()
    {
        var report = new List<string>();
        
        report.Add("═══════════════════════════════════════════════════════════");
        report.Add("              口径模板对比报告                           ");
        report.Add("═══════════════════════════════════════════════════════════");
        report.Add($"模板1: {TemplateId1}");
        report.Add($"模板2: {TemplateId2}");
        report.Add($"对比时间: {ComparedAt:yyyy-MM-dd HH:mm:ss}");
        report.Add("");
        
        if (!SignificantDifferences.Any())
        {
            report.Add("【对比结果】");
            report.Add("  ✓ 无显著差异，口径一致");
        }
        else
        {
            report.Add($"【差异汇总】共 {SignificantDifferences.Count} 项显著差异");
            report.Add($"  总金额差异: ¥{TotalDifference:F2}");
            report.Add($"  百分比差异: {PercentageDifference:P2}");
            report.Add("");
            
            report.Add("【差异明细】");
            foreach (var diff in SignificantDifferences)
            {
                report.Add($"  {diff.Category}.{diff.Field}");
                report.Add($"    模板1: {diff.OldValue}");
                report.Add($"    模板2: {diff.NewValue}");
                report.Add($"    说明: {diff.Description}");
            }
        }
        
        report.Add("═══════════════════════════════════════════════════════════");
        
        return string.Join(Environment.NewLine, report);
    }
}

public class TemplateSearchCriteria
{
    public string? Name { get; set; }
    public string? Category { get; set; }
    public List<string>? Tags { get; set; }
    public TemplateType? Type { get; set; }
    public TemplateSource? Source { get; set; }
    public DateTime? CreatedAfter { get; set; }
    public DateTime? CreatedBefore { get; set; }
    public string? CreatedBy { get; set; }
    public int? MinUsageCount { get; set; }
    public bool? IsActive { get; set; }
}

public class TemplateManagementService
{
    private readonly List<CalculationTemplate> _templates = new();
    
    public CalculationTemplate CreateTemplate(
        string name,
        string category,
        TemplateType type,
        TemplateSnapshot snapshot,
        string createdBy,
        string description = "")
    {
        var template = new CalculationTemplate
        {
            TemplateName = name,
            TemplateDescription = description,
            Category = category,
            Type = type,
            Source = TemplateSource.Manual,
            CreatedAt = DateTime.UtcNow,
            CreatedBy = createdBy,
            Snapshot = snapshot,
            IsActive = true
        };
        
        _templates.Add(template);
        return template;
    }
    
    public CalculationTemplate? GetTemplate(string templateId)
    {
        return _templates.FirstOrDefault(t => t.TemplateId == templateId);
    }
    
    public List<CalculationTemplate> SearchTemplates(TemplateSearchCriteria criteria)
    {
        var query = _templates.AsEnumerable();
        
        if (!string.IsNullOrEmpty(criteria.Name))
            query = query.Where(t => t.TemplateName.Contains(criteria.Name));
        
        if (!string.IsNullOrEmpty(criteria.Category))
            query = query.Where(t => t.Category == criteria.Category);
        
        if (criteria.Type.HasValue)
            query = query.Where(t => t.Type == criteria.Type.Value);
        
        if (criteria.Source.HasValue)
            query = query.Where(t => t.Source == criteria.Source.Value);
        
        if (criteria.CreatedAfter.HasValue)
            query = query.Where(t => t.CreatedAt >= criteria.CreatedAfter.Value);
        
        if (criteria.CreatedBefore.HasValue)
            query = query.Where(t => t.CreatedAt <= criteria.CreatedBefore.Value);
        
        if (!string.IsNullOrEmpty(criteria.CreatedBy))
            query = query.Where(t => t.CreatedBy == criteria.CreatedBy);
        
        if (criteria.MinUsageCount.HasValue)
            query = query.Where(t => t.UsageCount >= criteria.MinUsageCount.Value);
        
        if (criteria.IsActive.HasValue)
            query = query.Where(t => t.IsActive == criteria.IsActive.Value);
        
        return query.OrderByDescending(t => t.LastUsedAt ?? t.CreatedAt).ToList();
    }
    
    public CalculationTemplate UpdateTemplate(string templateId, Action<CalculationTemplate> updateAction)
    {
        var template = GetTemplate(templateId);
        if (template == null)
            throw new ArgumentException("Template not found");
        
        updateAction(template);
        template.Versions.Add(new TemplateVersion
        {
            VersionNumber = template.Versions.Count + 1,
            CreatedAt = DateTime.UtcNow,
            CreatedBy = "System",
            ChangeNote = "Template updated",
            Snapshot = template.Snapshot
        });
        
        return template;
    }
    
    public bool DeleteTemplate(string templateId)
    {
        var template = GetTemplate(templateId);
        if (template == null) return false;
        
        template.IsActive = false;
        return true;
    }
    
    public void RecordUsage(string templateId)
    {
        var template = GetTemplate(templateId);
        if (template != null)
        {
            template.UsageCount++;
            template.LastUsedAt = DateTime.UtcNow;
        }
    }
    
    public List<CalculationTemplate> GetTemplatesByOrder(string orderId)
    {
        return _templates
            .Where(t => t.Snapshot.OrderSnapshot != null && 
                       t.Snapshot.OrderId == orderId)
            .ToList();
    }
    
    public List<CalculationTemplate> GetSimilarTemplates(TemplateSnapshot snapshot, int limit = 10)
    {
        return _templates
            .Where(t => t.IsActive)
            .Select(t => new 
            { 
                Template = t, 
                Score = CalculateSimilarity(t.Snapshot, snapshot) 
            })
            .Where(x => x.Score > 0.5m)
            .OrderByDescending(x => x.Score)
            .Take(limit)
            .Select(x => x.Template)
            .ToList();
    }
    
    private decimal CalculateSimilarity(TemplateSnapshot t1, TemplateSnapshot t2)
    {
        var score = 0m;
        var total = 0m;
        
        if (t1.OrderSnapshot.OriginalAmount == t2.OrderSnapshot.OriginalAmount)
            score += 1m;
        total += 1m;
        
        if (t1.OrderSnapshot.ItemCount == t2.OrderSnapshot.ItemCount)
            score += 1m;
        total += 1m;
        
        if (t1.OrderSnapshot.Member?.Level == t2.OrderSnapshot.Member?.Level)
            score += 1m;
        total += 1m;
        
        var commonCoupons = t1.CouponsSnapshot
            .Select(c => c.CouponId)
            .Intersect(t2.CouponsSnapshot.Select(c => c.CouponId))
            .Count();
        
        var totalCoupons = t1.CouponsSnapshot.Count + t2.CouponsSnapshot.Count;
        if (totalCoupons > 0)
        {
            score += (2m * commonCoupons / totalCoupons);
            total += 1m;
        }
        
        return total > 0 ? score / total : 0;
    }
}

public class UnifiedExplanation
{
    public string ExplanationId { get; set; } = Guid.NewGuid().ToString();
    
    public string OrderId { get; set; } = string.Empty;
    public string TemplateId { get; set; } = string.Empty;
    
    public DateTime GeneratedAt { get; set; }
    public string GeneratedBy { get; set; } = string.Empty;
    
    public AudienceType Audience { get; set; }
    
    public UnifiedExplanationContent Content { get; set; } = new();
    
    public Dictionary<string, object> RawData { get; set; } = new();
    
    public string GenerateForAudience(AudienceType audience)
    {
        return audience switch
        {
            AudienceType.Customer => GenerateCustomerExplanation(),
            AudienceType.CustomerService => GenerateCustomerServiceExplanation(),
            AudienceType.Operations => GenerateOperationsExplanation(),
            AudienceType.Finance => GenerateFinanceExplanation(),
            _ => GenerateDefaultExplanation()
        };
    }
    
    public string GenerateCustomerExplanation()
    {
        var lines = new List<string>();
        lines.Add($"订单号: {OrderId}");
        lines.Add($"应付金额: ¥{Content.FinalAmount:F2}");
        
        if (Content.AppliedDiscounts.Any())
        {
            lines.Add("已享受优惠:");
            foreach (var discount in Content.AppliedDiscounts)
            {
                lines.Add($"  · {discount.Name}: -¥{discount.Amount:F2}");
            }
        }
        
        if (!string.IsNullOrEmpty(Content.CustomerMessage))
            lines.Add(Content.CustomerMessage);
        
        return string.Join(Environment.NewLine, lines);
    }
    
    public string GenerateCustomerServiceExplanation()
    {
        var lines = new List<string>();
        lines.Add($"【客服口径】订单号: {OrderId}");
        lines.Add($"原始金额: ¥{Content.OriginalAmount:F2}");
        lines.Add($"优惠金额: -¥{Content.TotalDiscount:F2}");
        lines.Add($"应付金额: ¥{Content.FinalAmount:F2}");
        
        lines.Add("");
        lines.Add("【优惠明细】");
        foreach (var discount in Content.DiscountDetails)
        {
            lines.Add($"  {discount.Type}: ¥{discount.Amount:F2}");
            lines.Add($"    原因: {discount.Reason}");
        }
        
        if (Content.UnavailableCoupons.Any())
        {
            lines.Add("");
            lines.Add("【不可用券】");
            foreach (var coupon in Content.UnavailableCoupons)
            {
                lines.Add($"  · {coupon.Name}: {coupon.Reason}");
            }
        }
        
        return string.Join(Environment.NewLine, lines);
    }
    
    public string GenerateOperationsExplanation()
    {
        var lines = new List<string>();
        lines.Add($"【运营口径】订单号: {OrderId}");
        lines.Add($"原始金额: ¥{Content.OriginalAmount:F2}");
        lines.Add($"总优惠: -¥{Content.TotalDiscount:F2}");
        lines.Add($"优惠率: {Content.DiscountRate:P2}");
        lines.Add($"应付金额: ¥{Content.FinalAmount:F2}");
        
        lines.Add("");
        lines.Add("【应用规则】");
        foreach (var rule in Content.AppliedRules)
        {
            lines.Add($"  · {rule.RuleName}: 贡献 ¥{rule.Contribution:F2}");
        }
        
        lines.Add("");
        lines.Add("【口径快照ID】: {TemplateId}");
        lines.Add($"【生成时间】: {GeneratedAt:yyyy-MM-dd HH:mm:ss}");
        
        return string.Join(Environment.NewLine, lines);
    }
    
    public string GenerateFinanceExplanation()
    {
        var lines = new List<string>();
        lines.Add($"【财务口径】订单号: {OrderId}");
        lines.Add($"商品总额: ¥{Content.OriginalAmount:F2}");
        lines.Add($"运费: ¥{Content.Freight:F2}");
        lines.Add($"应付总额: ¥{Content.FinalAmount + Content.Freight:F2}");
        lines.Add($"优惠总额: ¥{Content.TotalDiscount:F2}");
        lines.Add($"净应付: ¥{Content.FinalAmount:F2}");
        
        lines.Add("");
        lines.Add("【优惠明细(财务口径)】");
        foreach (var discount in Content.DiscountDetails)
        {
            lines.Add($"  {discount.Type}: ¥{discount.Amount:F2} (税率处理: {discount.TaxTreatment})");
        }
        
        lines.Add("");
        lines.Add($"【口径快照ID】: {TemplateId}");
        lines.Add($"【快照时间】: {GeneratedAt:yyyy-MM-dd HH:mm:ss}");
        
        return string.Join(Environment.NewLine, lines);
    }
    
    private string GenerateDefaultExplanation()
    {
        return GenerateCustomerServiceExplanation();
    }
}

public enum AudienceType
{
    Customer,
    CustomerService,
    Operations,
    Finance,
    Audit
}

public class UnifiedExplanationContent
{
    public decimal OriginalAmount { get; set; }
    public decimal TotalDiscount { get; set; }
    public decimal FinalAmount { get; set; }
    public decimal Freight { get; set; }
    public decimal DiscountRate { get; set; }
    
    public List<AppliedDiscountInfo> AppliedDiscounts { get; set; } = new();
    public List<DiscountDetailInfo> DiscountDetails { get; set; } = new();
    public List<UnavailableCouponInfo> UnavailableCoupons { get; set; } = new();
    public List<AppliedRuleInfo> AppliedRules { get; set; } = new();
    
    public string CustomerMessage { get; set; } = string.Empty;
    public string OperationsNote { get; set; } = string.Empty;
    public string FinanceNote { get; set; } = string.Empty;
}

public class AppliedDiscountInfo
{
    public string Name { get; set; } = string.Empty;
    public decimal Amount { get; set; }
}

public class DiscountDetailInfo
{
    public string Type { get; set; } = string.Empty;
    public decimal Amount { get; set; }
    public string Reason { get; set; } = string.Empty;
    public string TaxTreatment { get; set; } = "正常";
}

public class UnavailableCouponInfo
{
    public string Name { get; set; } = string.Empty;
    public string Reason { get; set; } = string.Empty;
}

public class AppliedRuleInfo
{
    public string RuleName { get; set; } = string.Empty;
    public decimal Contribution { get; set; }
}